# Generated by Django 5.2.4 on 2025-07-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('mentor', 'Mentor'), ('admin', 'Admin'), ('teacher', 'Teacher')], max_length=10),
        ),
    ]
