# Generated by Django 5.2.4 on 2025-07-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_badge_customuser_level_customuser_xp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='verification_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
