# Generated by Django 5.2.4 on 2025-07-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_assignment_course_test_data_course_text_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
